### ISSUE TITLE
TypeName or VarType?

### ISSUE THREAD

**Issue by PeterSwinkels** [dzzie/libs#1]
I see you use the TypeName function to check a variable's datatype. Wouldn't it more reliable and efficient to use the VarType function? The values it returns are listed in the VbVarType enumeration.

**Comment by dzzie** [comment]
I have actually never used vartype before. Always seemed like there had to be a better way. Not sure about more reliable, but I am sure it will be more efficient , will change them over someday thanks :)

**Comment by PeterSwinkels** [comment]
I believe TypeName may be unreliable because it's possible the exact name returned may depend on the local. I would need to check to be sure. Also, your checks are case-sensitive.

**Comment by dzzie** [comment]
Looks like the type names are hard coded in the dll for intrinsic types

 v12 = g_rgstrTypeNames_S41673[v4];
.data:66116070 _g_rgstrTypeNames$S41673 dd offset ...
.text:6609B6EC                 text 'Single',0

typos have caused problems

**Comment by PeterSwinkels** [comment]
How did you extract that information? Also from which dll?

**Comment by dzzie** [comment]
it is in msvbvm60.dll  I created a small exe

dim i as long
msgbox typename(i)

then started it under ollydbg and set a breakpoint on the msvbvm60.dll export rtcTypeName,
hit run, breakpoint hits, then started single stepping until I saw this:

6608D8F9   8B3CBD 70601166  MOV EDI,DWORD PTR DS:[EDI*4+66116070]   

Thats where it looks up the string name from the numeric type as an offset into the array at
66116070, looking at that address in olly dump window view as long address shows:

$ ==>    >6609B724  UNICODE "Empty"   ; element 0   Const vbEmpty = 0
$+4      >6609B718  UNICODE "Null"         ; element 1  Const vbNull = 1
$+8      >6609B708  UNICODE "Integer"
$+C      >6609B6FC  UNICODE "Long"
$+10     >6609B6EC  UNICODE "Single"
$+14     >6609B6DC  UNICODE "Double"
$+18     >6609B6C8  UNICODE "Currency"
$+1C     >6609B6BC  UNICODE "Date"
$+20     >6609B6AC  UNICODE "String"
$+24     >6609B69C  UNICODE "Object"  ; element 9   Const vbObject = 9
$+28     >6609B690  UNICODE "Error"
$+2C     >6609B680  UNICODE "Boolean"
$+30     >6609B670  UNICODE "Variant"
$+34     >6609B660  UNICODE "Unknown"
$+38     >6609B650  UNICODE "Decimal"
$+3C     >66001E62  MSVBVM60.66001E62  -> 00000000  element 15
$+40     >66001E62  MSVBVM60.66001E62 
$+44     >6609B644  UNICODE "Byte"              Const vbByte = 17 
$+48     >6609B634  UNICODE "Record"

constants 15 and 16 are undefined, the record type at element 18 does not show up in the object browser
which is interesting. 

My offsets for this version of the vb runtime with debug symbols: http://sandsprite.com/vb-reversing/files/msvbvm60.zip

**Comment by PeterSwinkels** [comment]
ollydbg? I should check that out some time. I can't download your zip file.

**Comment by dzzie** [comment]
classic 32bit asm level debugger: https://www.ollydbg.de/
x64dbg is another great one (with a 32bit version too): https://x64dbg.com/

av vendors are always blocking my downloads I cant keep up so i gave up. its funny because thats literally just two files from microsoft. they are probably blocking based on my domain or something then.

**Comment by PeterSwinkels** [comment]
I see. Thanks.
